spring:
  application:
    name: test-case
  data:
    mongodb:
      database: sensors
      port: 27017
      host: localhost

server:
  port: 8090
  servlet:
    context-path: /test-case

logging:
  level:
    com.garcia.sergio.testcase.infrastructure.mongo: DEBUG