version: '3.7'

services:
  mongo:
    image: "mongo:7"
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sensors
    volumes:
      - ./schema.js:/docker-entrypoint-initdb.d/schema.js:ro
